services:
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data


  mongodb:
    image: mongo
    ports:
      - 27017:27017
    env_file:
      - .env.dev
    volumes:
      - mongo-data:/data/db

  backend:
    image: backend-mm2:1.0
    command: npx tsnd --respawn --transpile-only --watch backend backend/index.ts
    ports:
      - 5500:5500
    volumes:
      - ./shared:/shared
      - ./config:/config
      - ./backend:/backend
    env_file:
      - .env.dev
    depends_on:
      - redis
      - mongodb

  scraper: 
    image: scraper-mm2:1.0
    command: npx tsnd --respawn --transpile-only --watch scraper scraper/index.ts
    volumes:
      - ./shared:/shared
      - ./config:/config
      - ./scraper:/scraper
    env_file:
      - .env.dev
    depends_on:
      - redis
      - backend
  
  bot:
    image: bot-mm2:1.0
    command: npx tsnd --respawn --transpile-only --watch bot bot/index.ts
    volumes:
      - ./shared:/shared
      - ./config:/config
      - ./bot:/bot
    env_file:
      - .env.dev
    depends_on:
      - redis
      - backend

volumes:
  mongo-data:
  redis-data: