services:
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data


  mongodb:
    image: mongo
    ports:
      - 27017:27017
    env_file:
      - ../.env.dev
    volumes:
      - mongo-data:/data/db

  backend:
    image: backend-mm2:4.0.0
    command: npm run start:dev
    ports:
      - 5500:5500
    volumes:
      - ../backend:/app
    env_file:
      - ../.env.dev
    depends_on:
      - redis
      - mongodb

  scraper: 
    image: scraper-mm2:4.0.0
    command: npx tsx watch src/index.ts
    volumes:
      - ../scraper:/app
    env_file:
      - ../.env.dev
    depends_on:
      - redis
      - backend
  
  bot:
    image: bot-mm2:4.0.0
    command: npx tsx watch src/index.ts
    volumes:
      - ../bot:/app
    env_file:
      - ../.env.dev
    depends_on:
      - redis
      - backend

volumes:
  mongo-data:
  redis-data:
