services:
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  backend:
    image: dexagon/backend-mm2:2.3.2
    ports:
      - 5500:5500
    env_file:
      - .env.prod
    depends_on:
      - redis

  scraper: 
    image: dexagon/scraper-mm2:2.3.2
    env_file:
      - .env.prod
    depends_on:
      - redis
      - backend
  
  bot:
    image: dexagon/bot-mm2:2.3.2
    env_file:
      - .env.prod
    depends_on:
      - redis
      - backend

volumes:
  redis-data:
    driver: local